# Site settings
title: Cybertron Iacon
subtitle: Autobots, transform and roll out!
description: I wanna be the challenger.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.piddnad.cn" # 你的域名
page_no_title: "Piddnad's Blog" # 文章无标题时默认显示内容
beian: # "备案号"
email: piddnad@gmail.com

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md"]
# gems: [jekyll-paginate]
plugins:
  - jekyll-paginate

markdown: kramdown  
highlighter: rouge
kramdown:
  input: GFM

# Pageinate settings
paginate: 7 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: # true
google_search: true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 标签
    directory: tags/
    icon: icon-history
  - page: 关于
    directory: about/
    icon: icon-about
  # - page: 历史
  #   directory: history/
  #   icon: icon-history
  # - page: 订阅
  #   directory: feed.xml
  #   icon: icon-rss

# Link settings
links: # 友情链接
  - title: Ama2in9
    url: https://ama2in9.top/
  - title: Simon
    url: https://www.simonyy.com/
  # - title: site-name3
  #   url: http://www.example3.com/

valine:
  enable: true
  app_id:  YjUidFlyYePITR34EyBWUFRG-gzGzoHsz
  app_key: bTB060geL43WbUhJucnuquBo
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  visitor: true
  avatar: retro
  placeholder: Say something~~
  guest_info: nick, mail, link
  pageSize: 10