# Site settings
title: Cybertron Iacon
subtitle: Autobots, transform and roll out!
description: I wanna be the challenger.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://piddnad.github.io" # 你的域名
page_no_title: "Piddnad's Blog" # 文章无标题时默认显示内容
beian: # "备案号"
email: piddnad@gmail.com

# Build settings
permalink: /:year/:month/:day/:title/
exclude: ["README.md", "changelog.md"]
# gems: [jekyll-paginate]
plugins:
  - jekyll-paginate

markdown: kramdown  
highlighter: rouge
kramdown:
  input: GFM

# Pageinate settings
paginate: 10 # 分页大小
paginate_path: "page/:num/"

# Search settings
baidu_search: true
google_search: # true

# Menu settings
menu:
  - page: 首页
    directory: .
    icon: icon-home
  - page: 归档
    directory: archives/
    icon: icon-archive
  - page: 关于
    directory: about/
    icon: icon-about
  - page: 历史
    directory: history/
    icon: icon-history
  # - page: 订阅
  #   directory: feed.xml
  #   icon: icon-rss

# Link settings
links: # 友情链接
  - title: Simon's Blog
    url: https://www.simonyy.com/
  # - title: site-name2
  #   url: http://www.example2.com/
  # - title: site-name3
  #   url: http://www.example3.com/
